# Generated by Django 5.1.4 on 2025-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_tag_movie_tags_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='tag',
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(related_name='series', to='api.tag'),
        ),
    ]
