# Generated by Django 5.1.4 on 2025-01-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_series_tag_series_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='series', to='api.tag'),
        ),
    ]
